drop table if exists users;

create table users (
  firstname text NOT NULL,
  lastname text NOT NULL,
  email text primary key NOT NULL,
  password text NOT NULL
);

drop table if exists concerts;

create table concerts (
  id INTEGER primary key generated by default as identity,
  date text,
  artist text,
  venue text,
  songs text,
  notes text,
  email text NOT NULL,
  foreign key (email) references users (email)
);