-- First, remove the table if it exists
drop table if exists concerts;

-- Create the table anew
create table concerts (
  id INTEGER primary key generated by default as identity,
  date text,
  artist text,
  venue text,
  songs text,
  notes text
);

-- "concerts_pkey" primary key