create table concerts (
  id INTEGER primary key generated by default as identity,
  date text,
  artist text,
  venue text,
  songs text,
  notes text,
  email text NOT NULL,
  foreign key (email) references users (email)
);